name: Build PaperlessUploader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Build:
    env:
      PYTHON_VERSION: "3.10"
    strategy:
      matrix:
        include:
          - os: macOS
            image: macos-latest
            python: ${{ env.PYTHON_VERSION }}
          - os: Windows
            image: windows-latest
            python: ${{ env.PYTHON_VERSION }}
      fail-fast: false

    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
#        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
#        pip install -r requirements.txt

    - name: Build app
      shell: bash
      run: |
        if [[ "${{ matrix.image }}" == macos-* ]]; then
          pyinstaller --noconsole --onefile --icon=MacOS/icon.icns MacOS/uploader.py
        elif [[ "${{ matrix.image }}" == windows-* ]]; then
          pyinstaller --noconsole --onefile --icon=Windows/paperless.ico Windows/uploader.py
        fi

#      pip install flake8 pytest
#
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings.
#        flake8 . --count --exit-zero --max-complexity=10 --statistics
#        
#    - name: Test with pytest
#      run: |
#        pytest

    - name: Delete .app folder on macOS
      if: ${{ startsWith(matrix.image, 'macos-') }}
      shell: bash
      run: rm -rf "${{ github.workspace }}/dist/"*.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PaperlessUploader_${{ matrix.os }}
        path: ${{ github.workspace }}/dist
        if-no-files-found: error

#    - name: Upload to release
#      if: tagged release from main
